# toml on target
#directoy di output dove si trovano i files .page
PostPerPage = 13
PageSplitterInputDir = "./src-test"
PostSourceDir = "./post-src"
OutDirPage = "D:\\Projects\\GItHub\\InvidositeHtmlgit\\src"
UiServerUrl = "localhost:4201"
WebGenWebPageDir = "D:\\Projects\\github\\InvidositeHtmlgit"
WebGenLocation = "D:\\ruby\\ruby_3_2_0\\bin"
WebgenOutIndexFile = "file:///D:/Projects/github/InvidositeHtmlgit/out/snapshot/index.html"